source 'http://rubygems.org'

gem 'rails', '3.0.20'

gem 'aegis', '~> 2.5.0'
gem 'aws-sdk', '~> 1.17.0'
gem 'cocaine', '~> 0.3.2'
gem 'bcrypt-ruby', '2.1.2', :require => 'bcrypt'
gem 'bing_translator', '~> 3.0.0'
gem 'dalli', '~> 2.6.4'
gem 'delayed_job_active_record', '~> 4.0.0'
gem 'devise', '~> 1.1.0'
gem 'dropbox-sdk', '~> 1.3', :require => 'dropbox_sdk'
gem 'fastercsv', '~> 1.5.0'
gem 'feedzirra', '~> 0.1.0'
gem 'formtastic', '~> 2.0.0'
gem 'globalize3', '~> 0.1.0'
gem 'hpricot', '~> 0.8.0'
gem 'http_accept_language', '~> 1.0.0'
gem 'i18n-js', '~> 2.1.0'
gem 'localized_country_select', '~> 0.9.2'
gem 'mime-types', '1.16', :require => 'mime/types'
gem 'mysql2', '~> 0.2.0'
gem 'oai', '~> 0.3.0'
gem 'paperclip', '~> 2.7.5'
gem 'sax-machine', '~> 0.1.0'
gem 'sitemap_generator', '~> 4.1.1'
gem 'smurf', '~> 1.0.0'
gem 'spawn', '~> 1.0.1', :git => 'git://github.com/rfc2822/spawn'
gem 'themes_for_rails', '~> 0.4.0'
gem 'thinking-sphinx', '~> 2.0.0', :require => 'thinking_sphinx'
gem 'will_paginate', '~> 3.0.0'

group :development do
  gem 'thin'
end
