source 'http://rubygems.org'

gem 'rails', '3.2.19'

gem 'acts-as-taggable-on', '2.4.1'
gem 'aegis', '~> 3.0.1', :git => 'https://github.com/JohnB/aegis.git', :ref => 'b1853a5'
gem 'aws-sdk', '~> 1.34.0'
gem 'bcrypt-ruby', '2.1.2', :require => 'bcrypt'
gem 'bing_translator', '~> 4.0.0'
gem 'dalli', '~> 2.6.4'
gem 'delayed_job_active_record', '~> 4.0.0'
gem 'devise', '~> 1.3.4'
gem 'dropbox-sdk', '~> 1.3.0', :require => 'dropbox_sdk'
gem 'europeana', '~> 0.1.0'
gem 'eventmachine', '~> 1.0.3'
gem 'fastercsv', '~> 1.5.0'
gem 'feedzirra', '~> 0.2.0'
gem 'flickraw', '~> 0.9.8'
gem 'formtastic', '~> 2.0.0'
gem 'google-api-client', '~> 0.6.4'
gem 'haml', '~> 4.0.3'
gem 'hpricot', '~> 0.8.0'
gem 'http_accept_language', '~> 1.0.0'
gem 'i18n', '~> 0.6.4'
gem 'i18n-js', '~> 2.1.0'
gem 'jquery-rails', '~> 2.1.4'
gem 'jquery-ui-rails', '~> 3.0'
gem 'legato', '~> 0.0.10'
gem 'localeapp', '~> 0.8.0'
gem 'localized_country_select', '~> 0.9.8'
gem 'mime-types', '1.16', :require => 'mime/types'
gem 'mysql2', '~> 0.3.0'
gem 'nokogiri', '~> 1.6.0'
gem 'oai', '~> 0.3.1', :path => 'vendor/gems/ruby-oai-0.3.1'
gem 'oauth2', '~> 0.9.2'
gem 'openskos', '~> 0.0.1', :git => 'https://github.com/europeana/openskos-client-ruby'
gem 'paperclip', '~> 4.2.0'
gem 'paperclip-meta', '~> 1.1.0'
gem 'progress_bar', '~> 1.0.0'
gem 'rails-i18n', '~> 3.0.0'
gem 'rdf', '~> 1.1.0'
gem 'rdf-rdfxml', '~> 1.1.0'
gem 'ruby-oembed', '~> 0.8.8'
gem 'sax-machine', '~> 0.2.0'
gem 'sitemap_generator', '~> 4.1.1'
gem 'sunspot_rails', '~> 2.1.0'
gem 'themes_for_rails', '~> 0.5.0'
gem 'thinking-sphinx', '~> 2.0.0', :require => 'thinking_sphinx'
gem 'will_paginate', '~> 3.0.0'

group :development do
  gem 'sunspot_solr', '~> 2.1.0'
  gem 'thin'
end

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails', ' ~> 3.2.3'
  # Uncomment for `compass watch` to work, i.e. in development
#  gem 'compass-rails', :git => 'https://github.com/Compass/compass-rails.git', :branch => '1-1-stable'
  # Uncomment for all other scenarios
  gem 'compass-rails', '~> 1.1.3'
  gem 'coffee-rails', ' ~> 3.2.1'
  gem 'uglifier', '~> 2.4.0'
end
