#!/bin/sh

#
# Create initial sphinx data, run this after a new config file is defined by webserver
# the new config file should already be in-place when this is run
#

# read local settings
. /usr/local/etc/gwa-sphinx.conf

echo 
echo ">>>>>>>>>>  running $0  <<<<<<<<<<<<"
echo


if [ -z $SPHINX_DB_DIR ]
then
   echo "***"
   echo "***"
   echo "***  Serious error, SPHINX_DB_DIR not defined, aborting"
   echo "***"
   exit 1
fi

touch $CRONBLOCKER

# ensure running cronjobs can complete
echo "==========>  Waiting $CRON_WAIT secs for cronjobs to complete"
sleep $CRON_WAIT

echo "==========>  Stoping sphinx"
$SPHINX_START_STOP_SCRIPT stop

echo "==========>  removing previous sphinx idx"
rm $SPHINX_DB_DIR/*

echo "==========>  force run hourly idx rebuild"
sudo -u $GWA_USER /usr/local/gwa-sphinx/do_cron_hourly

echo "==========>  force run minutely idx update"
sudo -u $GWA_USER /usr/local/gwa-sphinx/do_cron_minute

echo "==========>  Starting sphinx"
$SPHINX_START_STOP_SCRIPT start

rm $CRONBLOCKER
