version: "3"
services:
  db:
    image: 1418-db
    build:
      context: ./db
    expose:
    - "3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: europeana_1418
      MYSQL_USER: 1418
      MYSQL_PASSWORD: 1418pass
    volumes:
      - 1418-db-mysql:/var/lib/mysql
  gateway:
    image: 1418-gateway
    build:
      context: ./gateway
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../public:/usr/share/nginx/html
  search:
    image: 1418-search
    build:
      context: ./search
    expose:
    - "8983"
    volumes:
      - 1418-search-solr:/solr-4.10.0/server/1418/data
  web:
    image: 1418-web
    build:
      context: ..
    depends_on:
      - db
      - search
    expose:
    - "8080"
    links:
      - db
    environment:
      DATABASE_URL: mysql2://1418:1418pass@db/europeana_1418?utf8=true
      RAILS_ENV: production
      PORT: 8080
    volumes:
      - ../config:/app/config
      - ../public:/app/public
      - 1418-web-log:/app/log
  worker:
    image: 1418-worker
    build:
      context: ./worker
    command: bundle exec script/delayed_job run
    depends_on:
      - db
      - search
    links:
      - db
    environment:
      DATABASE_URL: mysql2://1418:1418pass@db/europeana_1418?utf8=true
      RAILS_ENV: production
    volumes:
      - ../config:/app/config
      - 1418-worker-log:/app/log
volumes:
  1418-web-log:
  1418-web-tmp:
  1418-worker-log:
  1418-worker-tmp:
  1418-db-mysql:
  1418-search-solr:
