version: "3"
services:
  web:
    image: 1418-web
    build:
      context: ..
    depends_on:
      - db
      - search
    ports:
    - "30000:3000"
    links:
      - db
    environment:
      DATABASE_URL: mysql2://1418:1418pass@db/europeana_1418?utf8=true
    volumes:
      - ../config:/app/config
  worker:
    image: 1418-worker
    build:
      context: ./worker
    command: bundle exec script/delayed_job run
    depends_on:
      - db
      - web
    links:
      - db
    environment:
      DATABASE_URL: mysql2://1418:1418pass@db/europeana_1418?utf8=true
    volumes:
      - ../config:/app/config
  db:
    image: 1418-db
    build:
      context: ./db
    ports:
    - "30001:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: europeana_1418
      MYSQL_USER: 1418
      MYSQL_PASSWORD: 1418pass
  search:
    image: 1418-search
    build:
      context: ./search
    ports:
    - "30002:8983"
