#!/bin/sh

#=======================================
#
#  Updates dev environment after svn changes
#  triggered from Hudson
#
#  Copyright: Europeana 2012
#  License: EUPL
#  By:  Jacob.Lundqvist@kb.nl
#

# need to run this as root...

export RAILS_ENV=production

echo
echo "=============   stoping apache   ==========="
echo
/etc/init.d/apache2 stop


echo
echo "=============   cd to source directory   ==========="
echo
cd /var/www/cococo


echo
echo "=============   remove old gemfile and stuff   ==========="
echo
rm Gemfile~
rm Gemfile.lock
rm .bundle -r


echo
echo "=============   svn update   ==========="
echo
sudo -u gwa svn up


echo
echo "=============   remove all gems   ==========="
echo
gem list | cut -d" " -f1 | xargs gem uninstall -aIx


echo
echo "=============   show installed gems   ==========="
echo
gem list


echo
echo "=============   install some basic gems   ==========="
echo
gem install rdoc-data bundler rake passenger

echo "The above warning rdoc-data is required for JRuby.... can be ignored"
echo "rdoc-data --install is being run"
rdoc-data --install

# the gem passenger is for connecting apache to a rails app.
# To actually update the apache stuff, you need to run:
#   passenger-install-apache2-module
# the output of this will help you with dependencies and apache config
# we dont rebuild the apache stuff each time, but we keep the passenger gem
# installed to ensure apache functionality



echo
echo "=============   show installed gems   ==========="
echo
gem list


echo
echo "=============   bundle install   ==========="
echo
rm Gemfile.lock
bundle install


echo
echo "=============   show installed gems   ==========="
echo
gem list


echo
echo "=============   update database schema  ==========="
echo
bundle exec rake db:migrate


echo
echo "=============   update translations.js  ==========="
echo
bundle exec rake i18n:js:export


echo
echo "==========   update sphinx config  ==========="
echo
bundle exec rake ts:config --trace



echo
echo "=============   updating sphinx server   ==========="
echo
ssh roo@$SPHINX_SERVER /usr/local/gwa-sphinx/update-sphinx


echo
echo "=============   starting apache   ==========="
echo
/etc/init.d/apache2 start
