#!/bin/sh

export RAILS_ENV=production
cd /var/www/cococo



case $1 in
    start)
        rake ts:start --trace
    ;;
    stop)
        rake ts:stop --trace
    ;;
    config)
        rake ts:config --trace
    ;;
    *)
       echo "Usage: spinhxd {start|stop|config}"
       exit 1
    ;;
esac
