#!/bin/sh

#=======================================
#
#  Updates dev environment after svn changes
#  triggered from Hudson
#
#  Copyright: Europeana 2012
#  License: EUPL
#  By:  Jacob.Lundqvist@kb.nl
#


# need to run this as root...



echo
echo "=============   svn update   ==========="
echo
cd /var/www/cococo
svn up

echo
echo "=============   remove all gems   ==========="
echo
gem list | cut -d" " -f1 | xargs gem uninstall -aIx


echo
echo "=============   install some basic gems   ==========="
echo
gem install bundle rake passenger

# the gem passenger is for connecting apache to a rails app.
# To actually update the apache stuff, you need to run:
#   passenger-install-apache2-module
# the output of this will help you with dependencies and apache config
# we dont rebuild the apache stuff each time, but we keep the passenger gem
# installed to ensure apache functionality

echo
echo "=============   bundle install   ==========="
echo
rm Gemfile.lock
bundle install
bundle exec rake db:migrate

echo
echo "=============   restarting apache   ==========="
echo
/etc/init.d/apache2 stop
/etc/init.d/apache2 start
