#!/bin/sh

#=======================================
#
#  Updates dev environment after svn changes
#  triggered from Hudson
#
#  Copyright: Europeana 2012
#  License: EUPL
#  By:  Jacob.Lundqvist@kb.nl
#


# need to run this as root...

cd /var/www/cococo
svn up
rm Gemfile.lock

# remove all gems, to ensure no remaining crapp...
gem list | cut -d" " -f1 | xargs gem uninstall -aIx

gem install bundle
bundle install


/etc/init.d/apache2 stop
/etc/init.d/apache2 start

