#!/bin/sh

export PATH=/var/lib/gems/1.8/bin:$PATH

# read local settings
. /usr/local/etc/gwa-sphinx.conf

if [ -e $WEB_UPDATE_BLOCKER ]
then
    echo "oncommit updates blocked by existance of" $WEB_UPDATE_BLOCKER
    exit 1
fi



export RAILS_ENV=production


echo
echo "=============   cd to source directory   ==========="
echo
cd $DEPLOY_DIR


echo
echo "=============   remove old gemfile and stuff   ==========="
echo
#rm Gemfile~
#rm Gemfile.lock
#rm .bundle -r


echo
echo "=============   svn update   ==========="
echo
sudo -u gwa svn up

echo
echo "=============   bundle update   ==========="
echo
bundle install --deployment

echo
echo "=============   stoping apache   ==========="
echo
/etc/init.d/apache2 stop

echo
echo "=============   clearing js and css min cache  ==========="
bundle exec rake assets:expire

echo
echo "=============   starting apache   ==========="
echo
/etc/init.d/apache2 start

